from django.core.management.base import BaseCommand
from voting.models import AllowedVoter

EMAILS = [
    "aisha.abdulkadir@strathmore.edu",
    "amarrah.aluodo@strathmore.edu",
    "gabriel.analoh@strathmore.edu",
    "naomi.bitta@strathmore.edu",
    "jones.brianna@strathmore.edu",
    "shantelle.david@strathmore.edu",
    "kipchumba.denis@strathmore.edu",
    "emanuel.dikirr@strathmore.edu",
    "issam.el@strathmore.edu",
    "bruce.gakuya@strathmore.edu",
    "comfort.gikunda@strathmore.edu",
    "leon.githui@strathmore.edu",
    "barack.habwe@strathmore.edu",
    "mukami.joan@strathmore.edu",
    "ndila.julie@strathmore.edu",
    "marvel.kabiru@strathmore.edu",
    "james.kanyua@strathmore.edu",
    "jessee.kariuki@strathmore.edu",
    "mohammed.khaleed@strathmore.edu",
    "mwongela.kiatira@strathmore.edu",
    "charlene.kiconco@strathmore.edu",
    "gabriella.kigen@strathmore.edu",
    "clarence.kinyua@strathmore.edu",
    "tatyana.kirera@strathmore.edu",
    "david.kitonga@strathmore.edu",
    "nicole.kituyi@strathmore.edu",
    "dwayne.kuria@strathmore.edu",
    "tracy.kuto@strathmore.edu",
    "melissa.lucas@strathmore.edu",
    "beverlyne.macharia@strathmore.edu",
    "sharon.wmacharia@strathmore.edu",
    "phyllis.maina@strathmore.edu",
    "andrew.makanda@strathmore.edu",
    "victor.makau@strathmore.edu",
    "donnel.masaba@strathmore.edu",
    "nimrod.mati@strathmore.edu",
    "makena.mbugua@strathmore.edu",
    "tamasha.mburu@strathmore.edu",
    "amos.mucha@strathmore.edu",
    "allen.muchiri@strathmore.edu",
    "nina.mudida@strathmore.edu",
    "trevor.mmugambi@strathmore.edu",
    "emmanuel.muriuki@strathmore.edu",
    "daniella.murugami@strathmore.edu",
    "rachael.mutethia@strathmore.edu",
    "israella.muteti@strathmore.edu",
    "brian.mmutua@strathmore.edu",
    "danielle.mwenda@strathmore.edu",
    "natasha.mwita@strathmore.edu",
    "tiffany.ndichu@strathmore.edu",
    "isaac.ndirangu@strathmore.edu",
    "mitchell.ngamau@strathmore.edu",
    "gerald.ngore@strathmore.edu",
    "violin.ngugi@strathmore.edu",
    "amara.ngunga@strathmore.edu",
    "nashipae.nina@strathmore.edu",
    "angela.tnjagi@strathmore.edu",
    "tabby.njalale@strathmore.edu",
    "immaculate.njambi@strathmore.edu",
    "gloria.njau@strathmore.edu",
    "lewis.cnjau@strathmore.edu",
    "angela.njonge@strathmore.edu",
    "shirleen.nzioka@strathmore.edu",
    "maynard.ochieng@strathmore.edu",
    "melissa.odiwuor@strathmore.edu",
    "christine.ojowi@strathmore.edu",
    "daniella.okello@strathmore.edu",
    "latifa.okoyo@strathmore.edu",
    "charlotte.ooga@strathmore.edu",
    "eustace.ooga@strathmore.edu",
    "valary.otieno@strathmore.edu",
    "leandre.saende@strathmore.edu",
    "sheikh.ramla@strathmore.edu",
    "sean.shundi@strathmore.edu",
    "cheryl.tanui@strathmore.edu",
    "fiona.tenai@strathmore.edu",
    "denis.towett@strathmore.edu",
    "michelle.tubei@strathmore.edu",
    "austin.wachira@strathmore.edu",
    "mark.kwachira@strathmore.edu",
    "sean.wachira@strathmore.edu",
    "furaha.wafula@strathmore.edu",
    "isaac.waliuba@strathmore.edu",
    "lola.wanjala@strathmore.edu",
    "anderson.wanjohi@strathmore.edu",
    "lina.washala@strathmore.edu",
    "valarie.waweru@strathmore.edu",
    "matu.yohance@strathmore.edu",
    "kelvin.mwangi@strathmore.edu",
    "alan.korir@strathmore.edu",
]


class Command(BaseCommand):
    help = "Preloads the approved voter list"

    def handle(self, *args, **options):
        created_count = 0
        for email in EMAILS:
            _, created = AllowedVoter.objects.get_or_create(email=email)
            if created:
                created_count += 1
        self.stdout.write(self.style.SUCCESS(
            f"Loaded {len(EMAILS)} emails, {created_count} newly added."
        ))